import { Award, Brain, Eye, Flame, Headphones, LockKeyhole, Medal, Trophy, Zap } from 'lucide-react';
import type { ComponentType } from 'react';
import type { ArenaState } from './ProgressTracking';

export type BadgeDefinition = { id: string; name: string; description: string; requirement: string; progress: (state: ArenaState) => { current: number; target: number }; icon: ComponentType<{ size?: number }> };

export const badgeDefinitions: BadgeDefinition[] = [
  { id: 'first-step', name: 'First Step', description: 'Complete your first challenge.', requirement: 'Complete 1 challenge.', progress: state => ({ current: Math.min(state.plays, 1), target: 1 }), icon: Medal },
  { id: 'one-day-streak', name: '1 Day Streak', description: 'Build your first daily learning streak.', requirement: 'Complete a daily challenge for 1 day.', progress: state => ({ current: Math.min(state.streak, 1), target: 1 }), icon: Flame },
  { id: 'sound-hunter', name: 'Sound Hunter', description: 'Practice sound skills consistently.', requirement: 'Complete 10 Sound Lab challenges.', progress: state => ({ current: Math.min(state.skillStats.sound.attempts, 10), target: 10 }), icon: Headphones },
  { id: 'focus-finder', name: 'Focus Finder', description: 'Train your visual attention.', requirement: 'Complete 20 Focus Zone challenges.', progress: state => ({ current: Math.min(state.skillStats.focus.attempts, 20), target: 20 }), icon: Eye },
  { id: 'memory-master', name: 'Memory Master', description: 'Reach 80% accuracy while building memory.', requirement: 'Reach 80% memory accuracy across 5 challenges.', progress: state => ({ current: Math.min(state.skillStats.memory.attempts, 5), target: 5 }), icon: Brain },
  { id: 'speedster', name: 'Speed Booster', description: 'Build accuracy in Speed Run challenges.', requirement: 'Reach 80% accuracy in Speed Run.', progress: state => ({ current: Math.min(state.skillStats.speed.bestAccuracy, 80), target: 80 }), icon: Zap },
  { id: 'personal-best', name: 'Personal Best', description: 'Reach a rating milestone in any skill.', requirement: 'Reach a rating of 800 in any skill.', progress: state => ({ current: Math.min(Math.max(...Object.values(state.ratings)), 800), target: 800 }), icon: Trophy },
];

export function BadgeProgressBar({ state, onOpen }: { state: ArenaState; onOpen: () => void }) {
  const unlocked = badgeDefinitions.filter(badge => state.achievements.includes(badge.id)).length;
  return <button onClick={onOpen} className="flex w-full items-center gap-4 rounded-2xl border border-[#f1d38a] bg-gradient-to-r from-[#fffaf0] to-[#fff1c7] p-4 text-left shadow-sm transition hover:shadow-md"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border-2 border-[#d4a941] bg-[#ffe8a3] text-[#9a6c0c]"><Trophy size={22} /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><span className="text-sm font-black text-text">Badges & Achievements</span><span className="text-xs font-black text-[#a47716]">{unlocked} / {badgeDefinitions.length}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#eadcae]"><div className="h-full rounded-full bg-[#d4a941] transition-all" style={{ width: `${unlocked / badgeDefinitions.length * 100}%` }} /></div><p className="mt-1 text-xs font-semibold text-text-muted">Open your collection and track the next achievement.</p></div></button>;
}

export function BadgeCollection({ state, onClose }: { state: ArenaState; onClose?: () => void }) {
  return <section className="rounded-2xl border border-border bg-surface p-5"><div className="flex items-center justify-between"><h2 className="font-black text-text"><Trophy size={20} className="mr-2 inline text-[#f2a93b]" />Badges</h2>{onClose && <button onClick={onClose} className="text-xs font-black text-text-muted">Close</button>}</div><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">{badgeDefinitions.map(badge => { const unlocked = state.achievements.includes(badge.id); const progress = badge.progress(state); const BadgeIcon = unlocked ? badge.icon : LockKeyhole; return <div key={badge.id} className={`${unlocked ? 'nb-earned-badge' : 'nb-locked-badge bg-gray-50'} rounded-xl p-3`}><div className="flex items-center gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full border-2 ${unlocked ? 'border-[#c99b2e] bg-[#ffe8a3] text-[#9a6c0c]' : 'border-gray-300 bg-gray-100 text-gray-400'}`}><BadgeIcon size={20} /></div><div><div className="text-sm font-black text-text">{badge.name}</div><div className="text-[11px] font-semibold text-text-muted">{unlocked ? 'UNLOCKED' : 'LOCKED'}</div></div>{unlocked && <span className="ml-auto text-xs font-black text-green-600">✓</span>}</div><p className="mt-2 text-xs font-semibold text-text-muted">{badge.description}</p><p className="mt-2 text-[11px] font-black text-text-muted">Requirement: {badge.requirement}</p><div className="mt-2 flex items-center justify-between text-[11px] font-black text-[#a47716]"><span>Progress</span><span>{progress.current} / {progress.target}</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[#d4a941]" style={{ width: `${Math.min(100, progress.current / progress.target * 100)}%` }} /></div></div>; })}</div></section>;
}
