import { useEffect, useState } from 'react';
import { Check, Clock3, Trophy, X } from 'lucide-react';
import type { Language } from '../../contexts/DyslexiaContext';

type Player = { name: string; rating: number; correct: number; index: number; finishedAt?: string };
type Battle = { status: 'countdown' | 'active' | 'complete'; startedAt: string; endsAt: string; question: { index: number; total: number; prompt: string; options: string[] } | null; you: Player; opponent: Player; result: { winnerId: string | null; yourRating: number; opponentRating: number; yourRatingChange: number; opponentRatingChange: number } | null };
type Props = { matchId: string; token: string; language: Language; userId: string; onExit: () => void; onResult: (result: { correct: number; total: number; seconds: number; delta: number }) => void };

const copy = {
  en: { you: 'YOU', opponent: 'OPPONENT', question: 'Question', choose: 'Choose an answer', wait: 'Waiting for the other player', win: 'WIN', loss: 'LOSS', draw: 'DRAW', score: 'Score', change: 'Rating change', back: 'Back to Arena', correct: 'Correct', wrong: 'Wrong' },
  hi: { you: 'आप', opponent: 'प्रतिद्वंद्वी', question: 'प्रश्न', choose: 'उत्तर चुनें', wait: 'दूसरे खिलाड़ी की प्रतीक्षा', win: 'जीत', loss: 'हार', draw: 'ड्रा', score: 'स्कोर', change: 'रेटिंग बदलाव', back: 'एरिना पर वापस जाएं', correct: 'सही', wrong: 'गलत' },
  mr: { you: 'तुम्ही', opponent: 'प्रतिस्पर्धक', question: 'प्रश्न', choose: 'उत्तर निवडा', wait: 'दुसऱ्या खेळाडूची प्रतीक्षा', win: 'विजय', loss: 'पराभव', draw: 'सामना बरोबरीत', score: 'गुण', change: 'गुणांमधील बदल', back: 'एरिनामध्ये परत जा', correct: 'बरोबर', wrong: 'चूक' },
};

export function BattleGame({ matchId, token, language, userId, onExit, onResult }: Props) {
  const t = copy[language];
  const [battle, setBattle] = useState<Battle | null>(null);
  const [countdown, setCountdown] = useState(3);
  const [selected, setSelected] = useState<number | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [started, setStarted] = useState<number | null>(null);
  const [secondsLeft, setSecondsLeft] = useState(120);

  const load = () => fetch(`http://localhost:4000/api/progress/battle/${matchId}`, { headers: { Authorization: `Bearer ${token}` } }).then(response => response.json()).then(data => { setBattle(data); if (data.status === 'active' && started === null) setStarted(Date.now()); }).catch(() => undefined);
  useEffect(() => { load(); const timer = window.setInterval(load, 1000); return () => window.clearInterval(timer); }, [matchId, token]);
  useEffect(() => { if (!battle || battle.status !== 'countdown') return; const timer = window.setInterval(() => { const remaining = Math.max(0, Math.ceil((new Date(battle.startedAt).getTime() - Date.now()) / 1000)); setCountdown(remaining); }, 100); return () => window.clearInterval(timer); }, [battle]);
  useEffect(() => { if (!battle || battle.status !== 'active') return; const timer = window.setInterval(() => setSecondsLeft(Math.max(0, Math.ceil((new Date(battle.endsAt).getTime() - Date.now()) / 1000))), 250); return () => window.clearInterval(timer); }, [battle]);
  useEffect(() => { if (battle?.status === 'complete' && battle.result && started !== null) onResult({ correct: battle.you.correct, total: battle.question?.total || 10, seconds: Math.max(1, Math.round((Date.now() - started) / 1000)), delta: battle.result.yourRatingChange }); }, [battle?.status]);

  const answer = (value: number) => { if (!battle?.question || submitting) return; setSelected(value); setSubmitting(true); fetch(`http://localhost:4000/api/progress/battle/${matchId}/answer`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ answer: value }) }).then(response => response.json()).then(data => { setBattle(data); setSelected(null); setSubmitting(false); }).catch(() => setSubmitting(false)); };
  if (!battle) return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#111827] text-xl font-black text-white">Connecting to battle...</div>;
  if (battle.status === 'complete' && battle.result) { const won = battle.result.winnerId === userId; const tied = battle.result.winnerId === null; const startingRating = battle.result.yourRating - battle.result.yourRatingChange; return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-auto bg-[#111827] p-5 text-white"><div className="w-full max-w-xl text-center"><Trophy className="mx-auto mb-5 text-[#f2a93b]" size={64} /><p className="text-sm font-black uppercase tracking-[0.3em] text-[#f2a93b]">{tied ? t.draw : won ? t.win : t.loss}</p><h1 className="mt-2 text-5xl font-black">{battle.you.correct} - {battle.opponent.correct}</h1><div className="mx-auto my-8 grid max-w-sm grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs font-bold text-white/60">{t.score}</p><p className="text-2xl font-black">{battle.you.correct} - {battle.opponent.correct}</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs font-bold text-white/60">{t.change}</p><p className="text-2xl font-black">{startingRating} → {battle.result.yourRating}</p><p className={`text-sm font-black ${battle.result.yourRatingChange >= 0 ? 'text-green-400' : 'text-red-400'}`}>{battle.result.yourRatingChange >= 0 ? '+' : ''}{battle.result.yourRatingChange}</p></div></div><button onClick={onExit} className="rounded-xl bg-[#e86f51] px-8 py-3 font-black">{t.back}</button></div></div>; }
  const remaining = battle.question?.total ? Math.round((battle.you.index / battle.question.total) * 100) : 0;
  return <div className="fixed inset-0 z-50 overflow-auto bg-[#111827] p-4 text-white sm:p-8"><div className="mx-auto max-w-4xl"><div className="grid grid-cols-2 gap-3"><PlayerBar label={t.you} player={battle.you} color="bg-[#4a90e2]" total={battle.question?.total || 20} /><PlayerBar label={t.opponent} player={battle.opponent} color="bg-[#e86f51]" total={battle.question?.total || 20} /></div>{battle.status === 'countdown' ? <div className="flex min-h-[60vh] flex-col items-center justify-center"><p className="text-sm font-black uppercase tracking-[0.35em] text-white/60">Get ready</p><div className="mt-4 text-9xl font-black text-[#f2a93b]">{countdown > 0 ? countdown : 'GO'}</div></div> : <div className="mx-auto mt-10 max-w-2xl rounded-3xl bg-white p-6 text-[#111827] shadow-2xl sm:p-10"><div className="mb-5 flex items-center justify-between text-xs font-black uppercase tracking-widest text-gray-500"><span><Clock3 className="mr-1 inline" size={14} />{t.question} {(battle.question?.index || 0) + 1}</span><span className="text-lg font-black text-[#e86f51]">{Math.floor(secondsLeft / 60)}:{String(secondsLeft % 60).padStart(2, '0')}</span></div><div className="mb-5 h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full bg-[#4a90e2] transition-all" style={{ width: `${remaining}%` }} /></div>{battle.question ? <><h1 className="text-2xl font-black sm:text-3xl">{battle.question.prompt}</h1><p className="mt-2 text-sm font-semibold text-gray-500">{t.choose}</p><div className="mt-7 grid gap-3">{battle.question.options.map((option, index) => <button key={option} disabled={submitting} onClick={() => answer(index)} className={`rounded-xl border-2 p-4 text-left font-black transition ${selected === index ? 'border-[#4a90e2] bg-blue-50' : 'border-gray-200 hover:border-[#4a90e2]'}`}>{String.fromCharCode(65 + index)}. {option}</button>)}</div></> : <div className="py-20 text-center font-black text-gray-500">{t.wait}...</div>}<div className="mt-8 border-t pt-5 text-center text-sm font-black text-gray-500">{t.opponent}: {battle.opponent.correct} {t.correct}</div></div>}</div></div>;
}

function PlayerBar({ label, player, color, total }: { label: string; player: Player; color: string; total: number }) { return <div className="rounded-2xl bg-white/10 p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-white/60">{label}</p><p className="font-black">{player.name}</p></div><div className="text-right"><p className="text-xl font-black">{player.rating}</p><p className="text-xs font-bold text-white/60">{player.correct} / {total}</p></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className={`h-full ${color} transition-all`} style={{ width: `${Math.min(100, player.index / total * 100)}%` }} /></div></div>; }
