import { useEffect, useState } from 'react';
import { Bell, Check, LoaderCircle, Swords, UserRound, X } from 'lucide-react';
import { motion } from 'framer-motion';
import type { Language } from '../../contexts/DyslexiaContext';

type Props = { skill: string; rating: number; language: Language; token: string | null; displayName?: string; onFound: (matchId: string) => void; onCancel: () => void };
type Status = 'scanning' | 'pending_acceptance' | 'invited' | 'matched' | 'error';
const labels = {
  en: { finding: 'Finding an opponent', sent: 'Challenge sent', subtitle: 'Scanning for students near your level', sentText: 'Your challenge is waiting for acceptance.', cancel: 'Cancel search', found: 'Match found!', ready: 'Ready to compete', you: 'You', start: 'Start challenge', waiting: 'Waiting for another player...', challenged: "You've been challenged!", wants: 'wants to compete with you in', accept: 'Accept', decline: 'Decline', missing: 'Your login session is missing. Please log in again.' },
  hi: { finding: 'प्रतिद्वंद्वी खोज रहे हैं', sent: 'चुनौती भेजी गई', subtitle: 'आपके स्तर के विद्यार्थियों को खोज रहे हैं', sentText: 'आपकी चुनौती स्वीकृति की प्रतीक्षा कर रही है।', cancel: 'खोज रद्द करें', found: 'मैच मिल गया!', ready: 'प्रतियोगिता के लिए तैयार', you: 'आप', start: 'चुनौती शुरू करें', waiting: 'दूसरे खिलाड़ी की प्रतीक्षा...', challenged: 'आपको चुनौती मिली है!', wants: 'आपके साथ प्रतियोगिता करना चाहते हैं:', accept: 'स्वीकार करें', decline: 'अस्वीकार करें', missing: 'आपका लॉगिन सत्र नहीं मिला। कृपया फिर से लॉगिन करें।' },
  mr: { finding: 'प्रतिस्पर्धक शोधत आहोत', sent: 'आव्हान पाठवले', subtitle: 'तुमच्या पातळीवरील विद्यार्थी शोधत आहोत', sentText: 'तुमचे आव्हान स्वीकारण्याची प्रतीक्षा करत आहे.', cancel: 'शोध रद्द करा', found: 'सामना सापडला!', ready: 'स्पर्धेसाठी तयार', you: 'तुम्ही', start: 'आव्हान सुरू करा', waiting: 'दुसऱ्या खेळाडूची प्रतीक्षा...', challenged: 'तुम्हाला आव्हान मिळाले आहे!', wants: 'तुमच्यासोबत स्पर्धा करू इच्छितात:', accept: 'स्वीकारा', decline: 'नकार द्या', missing: 'तुमचे लॉगिन सत्र सापडले नाही। कृपया पुन्हा लॉगिन करा.' },
};

export function MatchmakingPanel({ skill, rating, language, token, displayName = 'Student', onFound, onCancel }: Props) {
  const t = labels[language]; const [status, setStatus] = useState<Status>('scanning'); const [error, setError] = useState(''); const [opponent, setOpponent] = useState<{ name: string; rating: number } | null>(null); const [queueId, setQueueId] = useState<string | null>(null);
  const handleData = (data: any) => { if (data.status === 'matched' && data.opponent && data.matchId) { onFound(data.matchId); } else if (data.status === 'pending_acceptance') { setOpponent(data.opponent); setStatus('pending_acceptance'); } else if (data.status === 'invited') { setOpponent(data.opponent); setStatus('invited'); } else if (data.status === 'waiting') { setQueueId(data.queueId); setStatus('scanning'); } };
  useEffect(() => { if (!token) { setError(t.missing); setStatus('error'); return; } let active = true; fetch('http://localhost:4000/api/progress/matchmaking/queue', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ skill, rating, mode: 'friendly', displayName }) }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not join queue'); return data; }).then(data => { if (active) handleData(data); }).catch(value => { if (active) { setError(value instanceof Error ? value.message : 'Could not find an opponent'); setStatus('error'); } }); return () => { active = false; }; }, [displayName, rating, skill, token]);
  useEffect(() => { if (!token || !queueId || status === 'matched' || status === 'error') return; const timer = window.setInterval(() => { fetch(`http://localhost:4000/api/progress/matchmaking/${queueId}`, { headers: { Authorization: `Bearer ${token}` } }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Matchmaking check failed'); return data; }).then(handleData).catch(value => { setError(value instanceof Error ? value.message : 'Matchmaking check failed'); setStatus('error'); }); }, 1000); return () => window.clearInterval(timer); }, [queueId, status, token]);
  const respond = (action: 'accept' | 'decline') => { if (!token || !queueId) return; fetch(`http://localhost:4000/api/progress/matchmaking/${queueId}/${action}`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }).then(response => response.json()).then(data => action === 'accept' ? handleData(data) : onCancel()).catch(() => undefined); };
  const cancel = () => { if (token) fetch('http://localhost:4000/api/progress/matchmaking/queue', { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }).catch(() => undefined); onCancel(); };
  if (status === 'scanning') return <div className="nb-matchmaking-screen fixed inset-0 z-50 flex min-h-screen flex-col items-center justify-center overflow-hidden"><p className="absolute top-[17%] text-xs font-medium uppercase tracking-[0.18em] text-white/45">{t.finding}</p><div className="relative h-64 w-64"><div className="nb-radar-ring inset-0" /><div className="nb-radar-ring inset-[11%]" style={{ animationDelay: '-0.8s' }} /><div className="nb-radar-ring inset-[25%]" style={{ animationDelay: '-1.6s' }} /><div className="nb-radar-sweep" /><div className="absolute inset-0 flex items-center justify-center"><span className="text-5xl font-black tracking-[-0.12em] text-[#9df84a]">qb</span></div></div><button onClick={cancel} className="absolute bottom-[12%] rounded-xl border border-white/25 bg-white/10 px-7 py-3 text-xs font-black text-white shadow-[0_5px_0_rgba(255,255,255,0.16)] transition hover:bg-white/15">{t.cancel}</button></div>;
  return <div className="relative mx-auto flex min-h-[min(680px,calc(100vh-170px))] max-w-2xl items-center justify-center"><div className="w-full rounded-3xl border border-border bg-surface p-8 text-center shadow-xl"><div className="mx-auto mb-5 flex h-20 w-20 items-center justify-center rounded-full bg-blue-50 text-[#4a90e2]"><Swords size={38} /></div>{status === 'pending_acceptance' && <><h1 className="text-2xl font-black text-text">{t.sent}</h1><p className="mt-2 text-sm font-semibold text-text-muted">{t.sentText}</p>{opponent && <p className="mt-6 font-bold text-text">{opponent.name} · {opponent.rating}</p>}</>}{status === 'error' && <><h1 className="text-2xl font-black text-red-600">{error}</h1></>}{status !== 'error' && <button onClick={cancel} className="mt-4 text-sm font-bold text-text-muted">{t.cancel}</button>}</div>{status === 'invited' && opponent && <motion.div initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} className="fixed right-5 top-5 z-[100] w-[min(380px,calc(100vw-2rem))] rounded-2xl border border-blue-200 bg-white p-5 text-left shadow-2xl"><div className="flex items-start gap-3"><div className="rounded-xl bg-orange-100 p-2 text-orange-600"><Bell size={22} /></div><div><h2 className="font-black text-text">{t.challenged}</h2><p className="mt-1 text-sm text-text"><strong>{opponent.name}</strong> {t.wants} <strong>{skill}</strong>.</p><p className="mt-1 text-xs font-bold text-text-muted">⭐ {opponent.rating}</p></div></div><div className="mt-4 flex gap-2"><button onClick={() => respond('accept')} className="flex-1 rounded-xl bg-green-500 py-2.5 text-sm font-black text-white"><Check size={15} className="mr-1 inline" />{t.accept}</button><button onClick={() => respond('decline')} className="flex-1 rounded-xl bg-gray-100 py-2.5 text-sm font-black text-text"><X size={15} className="mr-1 inline" />{t.decline}</button></div></motion.div>}</div>;
}
