import { useEffect, useMemo, useState } from 'react';
import { Brain, Check, Eye, Flame, Gamepad2, Headphones, LockKeyhole, Swords, Target, Trophy, Zap } from 'lucide-react';
import { useDyslexia } from '../../contexts/DyslexiaContext';
import { useAuth } from '../../contexts/AuthContext';
import { ProgressGame, type GameResult } from './ProgressGame';
import { MatchmakingPanel } from './MatchmakingPanel';
import { BattleGame } from './BattleGame';
import { BadgeCollection, BadgeProgressBar, badgeDefinitions, type BadgeDefinition } from './BadgeCollection';

type SkillId = 'sound' | 'focus' | 'memory' | 'speed';
type Skill = { id: SkillId; icon: typeof Brain; name: string; construct: string; color: string; rating: number; delta: number };
export type ArenaState = { ratings: Record<SkillId, number>; skillStats: Record<SkillId, { bestAccuracy: number; attempts: number }>; plays: number; streak: number; lastPlayed: string; weeklyGain: number; days: string[]; dailyChallenges: string[]; achievements: string[]; acceptedChallenges: number; wins: number; losses: number; opponent: { name: string; rating: number } | null };
const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const today = () => new Date().toISOString().slice(0, 10);
const labels = {
  en: { arena: 'Your Reading Arena', daily: 'DAILY CHALLENGE', play: 'Play', playNow: 'Play now', streak: 'day streak', best: 'Best', week: 'this week', skills: 'Your skills', construct: 'Learning construct', peer: 'CHALLENGE A PEER', peerText: 'Find someone around your level.', find: 'Find opponent', you: 'You', accepted: 'accepted', activity: 'Weekly activity', challenges: 'challenges completed', rating: 'rating this week', achievements: 'Recent achievements', growth: 'Your growth', next: 'Recommended next', go: 'Go play', played: 'Played' },
  hi: { arena: 'आपका रीडिंग एरिना', daily: 'दैनिक चुनौती', play: 'खेलें', playNow: 'अभी खेलें', streak: 'दिनों की लकीर', best: 'सर्वश्रेष्ठ', week: 'इस सप्ताह', skills: 'आपके कौशल', construct: 'सीखने का कौशल', peer: 'साथी को चुनौती दें', peerText: 'अपने स्तर के किसी विद्यार्थी को खोजें।', find: 'प्रतिद्वंद्वी खोजें', you: 'आप', accepted: 'स्वीकृत', activity: 'साप्ताहिक गतिविधि', challenges: 'चुनौतियां पूरी', rating: 'इस सप्ताह रेटिंग', achievements: 'हाल की उपलब्धियां', growth: 'आपकी प्रगति', next: 'अगली सुझाई चुनौती', go: 'खेलने जाएं', played: 'खेला गया' },
  mr: { arena: 'तुमचे रीडिंग एरिना', daily: 'दैनिक आव्हान', play: 'खेळा', playNow: 'आता खेळा', streak: 'दिवसांची मालिका', best: 'सर्वोत्तम', week: 'या आठवड्यात', skills: 'तुमची कौशल्ये', construct: 'शिकण्याचे कौशल्य', peer: 'सहकाऱ्याला आव्हान द्या', peerText: 'तुमच्या पातळीवरील विद्यार्थी शोधा.', find: 'प्रतिस्पर्धी शोधा', you: 'तुम्ही', accepted: 'स्वीकारले', activity: 'साप्ताहिक उपक्रम', challenges: 'आव्हाने पूर्ण', rating: 'या आठवड्यातील गुण', achievements: 'अलीकडील यश', growth: 'तुमची प्रगती', next: 'पुढील सुचवलेले आव्हान', go: 'खेळायला जा', played: 'खेळले' },
} as const;

export function ProgressTracking() {
  const { language } = useDyslexia();
  const { user, token } = useAuth();
  const t = labels[language];
  const [game, setGame] = useState<{ skillId: SkillId; isMatch: boolean } | null>(null);
  const [battle, setBattle] = useState<{ matchId: string; skillId: SkillId } | null>(null);
  const [matchmaking, setMatchmaking] = useState<SkillId | null>(null);
  const [unlockedBadge, setUnlockedBadge] = useState<BadgeDefinition | null>(null);
  const [showBadges, setShowBadges] = useState(false);
  const storageKey = `neurobridge-learning-arena-v1:${user?.email || 'guest'}`;
  const [state, setState] = useState<ArenaState>(() => {
    const empty = { sound: 0, focus: 0, memory: 0, speed: 0 };
    const defaults = { ratings: empty, skillStats: { sound: { bestAccuracy: 0, attempts: 0 }, focus: { bestAccuracy: 0, attempts: 0 }, memory: { bestAccuracy: 0, attempts: 0 }, speed: { bestAccuracy: 0, attempts: 0 } }, plays: 0, streak: 0, lastPlayed: '', weeklyGain: 0, days: [], dailyChallenges: [], achievements: [], acceptedChallenges: 0, wins: 0, losses: 0, opponent: null };
    try { const saved = JSON.parse(localStorage.getItem(storageKey) || 'null'); return saved ? { ...defaults, ...saved, ratings: { ...empty, ...saved.ratings }, skillStats: { ...defaults.skillStats, ...saved.skillStats } } : defaults; } catch { return defaults; }
  });
  useEffect(() => { localStorage.setItem(storageKey, JSON.stringify(state)); }, [state, storageKey]);
  useEffect(() => { if (!token) return; fetch('http://localhost:4000/api/progress', { headers: { Authorization: `Bearer ${token}` } }).then(r => r.ok ? r.json() : null).then(data => { if (!data) return; setState(current => ({ ...current, ratings: { ...current.ratings, ...Object.fromEntries(Object.entries(data.skills || {}).map(([id, stats]: [string, any]) => [id, stats.rating])) }, skillStats: { ...current.skillStats, ...data.skills }, plays: data.completedChallenges ?? current.plays, streak: data.streak ?? current.streak, lastPlayed: data.lastPlayedDay ?? current.lastPlayed, days: data.activityDays ?? current.days, dailyChallenges: data.dailyChallenges ?? current.dailyChallenges, weeklyGain: data.arena?.weeklyGain ?? current.weeklyGain, achievements: data.achievements ?? current.achievements, acceptedChallenges: data.arena?.acceptedChallenges ?? current.acceptedChallenges, wins: data.arena?.wins ?? current.wins, losses: data.arena?.losses ?? current.losses, opponent: data.arena?.opponent ?? current.opponent })); }).catch(() => undefined); }, [token]);
  const skills: Skill[] = [
    { id: 'sound', icon: Headphones, name: language === 'hi' ? 'ध्वनि प्रयोगशाला' : language === 'mr' ? 'ध्वनी प्रयोगशाळा' : 'Sound Lab', construct: language === 'hi' ? 'ध्वन्यात्मक जागरूकता' : language === 'mr' ? 'ध्वन्यात्मक जागरूकता' : 'Phonological Awareness', color: '#e86f51', rating: state.ratings.sound, delta: state.skillStats.sound.bestAccuracy },
    { id: 'focus', icon: Eye, name: language === 'hi' ? 'फोकस ज़ोन' : language === 'mr' ? 'फोकस झोन' : 'Focus Zone', construct: language === 'hi' ? 'दृश्य ध्यान' : language === 'mr' ? 'दृश्य लक्ष' : 'Visual Attention', color: '#4a90e2', rating: state.ratings.focus, delta: state.skillStats.focus.bestAccuracy },
    { id: 'memory', icon: Brain, name: language === 'hi' ? 'मेमोरी वॉल्ट' : language === 'mr' ? 'मेमरी वॉल्ट' : 'Memory Vault', construct: language === 'hi' ? 'कार्यशील स्मृति' : language === 'mr' ? 'कार्यरत स्मरणशक्ती' : 'Working Memory', color: '#8b6fc5', rating: state.ratings.memory, delta: state.skillStats.memory.bestAccuracy },
    { id: 'speed', icon: Zap, name: language === 'hi' ? 'स्पीड रन' : language === 'mr' ? 'स्पीड रन' : 'Speed Run', construct: language === 'hi' ? 'प्रसंस्करण गति' : language === 'mr' ? 'प्रक्रिया वेग' : 'Processing Speed', color: '#f2a93b', rating: state.ratings.speed, delta: state.skillStats.speed.bestAccuracy },
  ];
  const daily = skills[new Date().getDate() % skills.length];
  const dailyDone = state.days.includes(today()) || state.dailyChallenges.includes(today());
  const weekActivity = DAYS.map((_, index) => state.days.includes(new Date(Date.now() - (6 - index) * 86400000).toISOString().slice(0, 10)));
  const complete = (result: GameResult) => { const date = today(); const previousAchievements = state.achievements; setState(value => ({ ...value, ratings: { ...value.ratings, [result.skillId]: Math.max(0, value.ratings[result.skillId] + result.delta) }, plays: value.plays + 1, streak: value.lastPlayed === date ? value.streak : value.streak + 1, lastPlayed: date, weeklyGain: value.weeklyGain + result.delta, days: value.days.includes(date) ? value.days : [...value.days, date], dailyChallenges: result.mode === 'practice' && !value.dailyChallenges.includes(date) ? [...value.dailyChallenges, date] : value.dailyChallenges, achievements: value.streak >= 1 || !value.lastPlayed || value.lastPlayed === date ? (value.achievements.includes('one-day-streak') ? value.achievements : [...value.achievements, 'one-day-streak']) : value.achievements })); if (token) fetch('http://localhost:4000/api/progress/games', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ skill: result.skillId, correct: result.correct, total: result.total, seconds: result.seconds, mode: result.mode, dailyKey: date }) }).then(response => response.json()).then(data => { const savedSkill = data.progress?.skills?.[result.skillId]; if (savedSkill) setState(value => ({ ...value, ratings: { ...value.ratings, [result.skillId]: savedSkill.rating }, skillStats: { ...value.skillStats, [result.skillId]: savedSkill } })); const newlyUnlocked = (data.progress?.achievements || []).find((id: string) => !previousAchievements.includes(id)); if (newlyUnlocked) setUnlockedBadge(badgeDefinitions.find(badge => badge.id === newlyUnlocked) || null); }).catch(() => undefined); };
  if (unlockedBadge) { const progress = unlockedBadge.progress(state); const BadgeIcon = unlockedBadge.icon; return <div className="fixed inset-0 z-[120] flex items-center justify-center overflow-hidden bg-[radial-gradient(circle_at_center,#513d12_0%,#17130a_42%,#050505_100%)] p-5"><div className="nb-badge-celebration-rays" /><span className="nb-badge-sparkle left-[12%] top-[22%]">✦</span><span className="nb-badge-sparkle right-[14%] top-[28%]" style={{ animationDelay: '0.25s' }}>✧</span><span className="nb-badge-sparkle bottom-[25%] left-[20%]" style={{ animationDelay: '0.5s' }}>✦</span><span className="nb-badge-sparkle bottom-[20%] right-[22%]" style={{ animationDelay: '0.75s' }}>✧</span><div className="nb-badge-unlock relative z-10 w-full max-w-lg text-center"><div className="nb-badge-shimmer" /><div className="nb-badge-celebration-icon relative mx-auto flex h-44 w-44 items-center justify-center rounded-full border-[10px] border-[#d4a941] bg-gradient-to-br from-[#fff3b0] via-[#f4cb5f] to-[#c88e17] text-[#805b08]"><BadgeIcon size={84} /></div><p className="relative mt-10 text-sm font-black uppercase tracking-[0.4em] text-[#ffe47e]">BADGE UNLOCKED!</p><h1 className="relative mt-3 text-4xl font-black text-white sm:text-5xl">{unlockedBadge.name}</h1><p className="relative mx-auto mt-4 max-w-md text-base font-semibold text-[#f8e9b5]">{unlockedBadge.description}</p><p className="relative mt-3 text-sm font-black text-[#ffe47e]">{progress.current} / {progress.target}</p><button onClick={() => setUnlockedBadge(null)} className="relative mt-9 rounded-xl bg-[#d4a941] px-9 py-3 font-black text-white shadow-[0_0_22px_rgba(212,169,65,0.65)] transition hover:bg-[#e4b84e]">Continue</button></div></div>; }
  if (showBadges) return <BadgeCollection state={state} onClose={() => setShowBadges(false)} />;
  if (battle && token) return <BattleGame matchId={battle.matchId} token={token} language={language} userId={String(user?.id)} onExit={() => setBattle(null)} onResult={result => { setState(value => ({ ...value, ratings: { ...value.ratings, [battle.skillId]: Math.max(0, value.ratings[battle.skillId] + result.delta) }, plays: value.plays + 1, weeklyGain: value.weeklyGain + result.delta })); }} />;
  if (matchmaking) { const skill = skills.find(item => item.id === matchmaking)!; return <MatchmakingPanel skill={skill.id} rating={skill.rating} language={language} token={token} displayName={user?.name} onFound={matchId => { setMatchmaking(null); setBattle({ matchId, skillId: skill.id }); }} onCancel={() => setMatchmaking(null)} />; }
  if (game) { const skill = skills.find(item => item.id === game.skillId)!; return <ProgressGame skillId={skill.id} skillName={skill.name} construct={skill.construct} rating={skill.rating} language={language} isMatch={game.isMatch} onComplete={complete} onExit={() => setGame(null)} />; }
  const badgeBar = <BadgeProgressBar state={state} onOpen={() => setShowBadges(true)} />;
  const cards = [
    <section key="daily" className="relative overflow-hidden rounded-2xl border border-orange-200 bg-gradient-to-r from-[#fff1dc] via-[#fff8ed] to-[#e8f4ff] p-5 shadow-sm"><div className="absolute right-5 top-4 text-5xl opacity-20">⚡</div><p className="text-xs font-black tracking-[0.18em] text-[#d87526]">{t.daily}</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-black text-text">{daily.name}</h2><p className="text-sm font-semibold text-text-muted">10 questions · {daily.construct}</p><p className="mt-2 text-2xl font-black text-text">{daily.rating}</p></div><button disabled={dailyDone} onClick={() => setGame({ skillId: daily.id, isMatch: false })} className="inline-flex items-center gap-2 rounded-xl bg-[#e86f51] px-5 py-3 text-sm font-black text-white disabled:opacity-50"><Gamepad2 size={17} /> {dailyDone ? '✓' : t.playNow}</button></div><p className="mt-3 text-xs font-bold text-text-muted">🔥 {state.streak} {t.streak} · {t.best}: {daily.rating} · +{state.weeklyGain} {t.week}</p></section>,
    <section key="skills"><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-black uppercase tracking-[0.16em] text-text-muted">{t.skills}</h2><span className="text-xs font-semibold text-text-muted">{t.construct}</span></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{skills.map(skill => { const Icon = skill.icon; return <article key={skill.id} className="rounded-2xl border border-border bg-surface p-4 shadow-sm"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="rounded-xl p-2.5" style={{ backgroundColor: `${skill.color}18`, color: skill.color }}><Icon size={21} /></div><div><h3 className="font-black text-text">{skill.name}</h3><p className="text-xs font-semibold text-text-muted">{skill.construct}</p></div></div><span className="rounded-full px-2 py-1 text-xs font-black" style={{ backgroundColor: `${skill.color}18`, color: skill.color }}>+{skill.delta}</span></div><div className="mt-4 flex items-end justify-between"><span className="text-3xl font-black text-text">{skill.rating}</span><button onClick={() => setGame({ skillId: skill.id, isMatch: false })} className="inline-flex items-center gap-1.5 rounded-lg bg-[#4a90e2] px-3 py-2 text-xs font-black text-white"><Gamepad2 size={14} /> {t.play}</button></div></article>; })}</div></section>,
    <div key="lower" className="grid grid-cols-1 gap-4 lg:grid-cols-[1.25fr_1fr]"><section className="rounded-2xl border border-border bg-[#f4f8ff] p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-black tracking-[0.16em] text-[#4a90e2]">{t.peer}</p><h2 className="mt-1 text-xl font-black text-text">{t.peerText}</h2><p className="mt-1 text-xs font-bold text-text-muted">{state.acceptedChallenges} {t.accepted}</p></div><Swords className="text-[#4a90e2]" size={28} /></div><div className="mt-5 flex items-center justify-center gap-5"><div className="text-center"><div className="text-xs font-bold text-text-muted">{t.you}</div><div className="text-3xl font-black text-[#4a90e2]">{daily.rating}</div></div><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-text-muted">VS</span><div className="text-center"><div className="text-xs font-bold text-text">{state.opponent?.name || 'No opponent yet'}</div><div className="text-3xl font-black text-[#e86f51]">{state.opponent?.rating ?? '—'}</div></div></div><button onClick={() => setMatchmaking(daily.id)} className="mt-5 w-full rounded-xl border border-[#4a90e2] bg-white py-2.5 text-sm font-black text-[#4a90e2]"><Swords size={15} className="mr-2 inline" />{t.find}</button></section><section className="rounded-2xl border border-border bg-surface p-5"><div className="flex items-center justify-between"><h2 className="font-black text-text">{t.activity}</h2><Target size={20} className="text-[#e86f51]" /></div><div className="mt-5 flex justify-between">{DAYS.map((day, i) => <div key={day} className="flex flex-col items-center gap-2"><span className={`flex h-6 w-6 items-center justify-center rounded-full text-xs ${weekActivity[i] ? 'bg-[#e86f51] text-white' : 'bg-gray-100 text-gray-400'}`}>{weekActivity[i] ? <Check size={13} /> : '·'}</span><span className="text-[10px] font-bold text-text-muted">{day}</span></div>)}</div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-border pt-4"><div><div className="text-xl font-black text-text">{state.plays}</div><div className="text-xs font-semibold text-text-muted">{t.challenges}</div></div><div><div className="text-xl font-black text-[#4a90e2]">+{state.weeklyGain}</div><div className="text-xs font-semibold text-text-muted">{t.rating}</div></div></div></section></div>,
    <div key="bottom" className="grid grid-cols-1 gap-4 lg:grid-cols-[1.25fr_1fr]"><section className="rounded-2xl border border-border bg-surface p-5"><div className="flex items-center justify-between"><h2 className="font-black text-text"><Trophy size={20} className="mr-2 inline text-[#f2a93b]" />{t.achievements}</h2></div><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">{badgeDefinitions.map(badge => { const unlocked = state.achievements.includes(badge.id); const progress = badge.progress(state); const BadgeIcon = unlocked ? badge.icon : LockKeyhole; return <div key={badge.id} className={`${unlocked ? 'nb-earned-badge' : 'nb-locked-badge bg-gray-50'} rounded-xl p-3`}><div className="flex items-center gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full border-2 ${unlocked ? 'border-[#c99b2e] bg-[#ffe8a3] text-[#9a6c0c]' : 'border-gray-300 bg-gray-100 text-gray-400'}`}><BadgeIcon size={20} /></div><div><div className="text-sm font-black text-text">{badge.name}</div><div className="text-[11px] font-semibold text-text-muted">{unlocked ? 'UNLOCKED' : 'LOCKED'}</div></div>{unlocked && <span className="ml-auto text-xs font-black text-green-600">✓</span>}</div><p className="mt-2 text-xs font-semibold text-text-muted">{badge.description}</p><p className="mt-2 text-[11px] font-black text-text-muted">Requirement: {badge.requirement}</p><div className="mt-2 flex items-center justify-between text-[11px] font-black text-[#a47716]"><span>Progress</span><span>{progress.current} / {progress.target}</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[#d4a941]" style={{ width: `${Math.min(100, progress.current / progress.target * 100)}%` }} /></div></div>; })}</div></section><section className="rounded-2xl border border-border bg-[#fff8ed] p-5"><div className="flex items-center justify-between"><h2 className="font-black text-text">{t.growth}</h2><Flame size={20} className="text-[#e86f51]" /></div><div className="mt-3 space-y-2">{skills.map(skill => <div key={skill.id} className="flex items-center justify-between rounded-lg bg-white/70 px-3 py-2"><span className="text-xs font-bold text-text">{skill.name}</span><span className="text-xs font-black text-[#e86f51]">↑ {skill.delta}%</span></div>)}</div><button onClick={() => setGame({ skillId: daily.id, isMatch: false })} className="mt-4 text-xs font-black text-[#e86f51]">{t.next} {t.go} →</button></section></div>,
  ];
  return <div className="max-w-5xl mx-auto pb-8 space-y-4"><div className="flex items-end justify-between px-1"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#e86f51]">{t.arena}</p><h1 className="text-3xl font-black text-text">{t.skills} <span className="text-[#e86f51]">🔥 {state.streak}</span></h1></div><div className="flex items-end gap-4"><div className="text-right text-xs font-bold text-text-muted">{state.plays} {t.played}<br />+{state.weeklyGain} {t.week}</div></div></div>{badgeBar}{cards.slice(0, 3)}</div>;
}
