import { useEffect, useState } from 'react';
import { ArrowLeft, Check, Clock3, Gamepad2, RotateCcw, Trophy, X } from 'lucide-react';
import type { Language } from '../../contexts/DyslexiaContext';

type SkillId = 'sound' | 'focus' | 'memory' | 'speed';
export type GameResult = { skillId: SkillId; correct: number; total: number; seconds: number; delta: number; mode: 'practice' | 'match' };
type Props = { skillId: SkillId; skillName: string; construct: string; rating: number; language: Language; isMatch?: boolean; onComplete: (result: GameResult) => void; onExit: () => void };
type Text = { title: string; exit: string; question: string; choose: string; next: string; submit: string; complete: string; score: string; accuracy: string; time: string; back: string; again: string; rating: string; change: string; correct: string; wrong: string; remember: string; repeat: string; clear: string; check: string; find: string; selected: string; match: string; yes: string; no: string };

const text: Record<Language, Text> = {
  en: { title: 'Challenge', exit: 'Exit', question: 'Question', choose: 'Choose an answer', next: 'Next', submit: 'Submit', complete: 'Challenge Complete!', score: 'Score', accuracy: 'Accuracy', time: 'Time', back: 'Back to arena', again: 'Play again', rating: 'Your rating', change: 'rating change', correct: 'That is correct!', wrong: 'Not quite. Keep going!', remember: 'Remember this sequence', repeat: 'Now reproduce it', clear: 'Clear', check: 'Check sequence', find: 'Find every', selected: 'selected', match: 'Does this pair match?', yes: 'Match', no: 'Not a match' },
  hi: { title: 'चुनौती', exit: 'बाहर जाएं', question: 'प्रश्न', choose: 'उत्तर चुनें', next: 'अगला', submit: 'जमा करें', complete: 'चुनौती पूरी!', score: 'स्कोर', accuracy: 'सटीकता', time: 'समय', back: 'एरिना पर वापस जाएं', again: 'फिर खेलें', rating: 'आपकी रेटिंग', change: 'रेटिंग बदलाव', correct: 'सही उत्तर!', wrong: 'अभी सही नहीं। कोशिश जारी रखें!', remember: 'इस क्रम को याद रखें', repeat: 'अब इसे दोहराएं', clear: 'साफ़ करें', check: 'क्रम जांचें', find: 'सभी खोजें', selected: 'चुने गए', match: 'क्या यह जोड़ी समान है?', yes: 'समान', no: 'समान नहीं' },
  mr: { title: 'आव्हान', exit: 'बाहेर पडा', question: 'प्रश्न', choose: 'उत्तर निवडा', next: 'पुढील', submit: 'सबमिट करा', complete: 'आव्हान पूर्ण!', score: 'गुण', accuracy: 'अचूकता', time: 'वेळ', back: 'एरिनामध्ये परत जा', again: 'पुन्हा खेळा', rating: 'तुमचे गुण', change: 'गुणांमधील बदल', correct: 'अचूक उत्तर!', wrong: 'अजून बरोबर नाही. प्रयत्न सुरू ठेवा!', remember: 'हा क्रम लक्षात ठेवा', repeat: 'आता तो पुन्हा तयार करा', clear: 'साफ करा', check: 'क्रम तपासा', find: 'सर्व शोधा', selected: 'निवडले', match: 'ही जोडी जुळते का?', yes: 'जुळते', no: 'जुळत नाही' },
};
const sound = [
  ['Which word starts with the same sound as SUN?', ['Moon', 'Sock', 'Tree', 'Fish'], 1], ['Which word ends with the same sound as CAT?', ['Cup', 'Map', 'Dog', 'Sun'], 1], ['Which word rhymes with LIGHT?', ['Late', 'Night', 'Lot', 'Lift'], 1], ['Which word starts with the same sound as BELL?', ['Ball', 'Moon', 'Fish', 'Tree'], 0], ['Which word rhymes with DAY?', ['Die', 'Toy', 'Say', 'Do'], 2], ['Which word starts with the same sound as FISH?', ['Fan', 'Goat', 'Ship', 'Tree'], 0], ['Which word rhymes with BOOK?', ['Back', 'Look', 'Bike', 'Bake'], 1], ['Which word starts with the same sound as STAR?', ['Stone', 'Car', 'Rain', 'Door'], 0], ['Which word ends with the same sound as RING?', ['Rain', 'Sing', 'Run', 'Rock'], 1], ['Which word rhymes with PLAY?', ['Pie', 'Day', 'Blue', 'Pool'], 1],
] as const;
const symbols = ['b', 'd', 'p', 'q'];
const wordPairs = [['CAT', 'CAT'], ['SUN', 'MOON'], ['BOOK', 'BOOK'], ['TREE', 'FREE'], ['FISH', 'FISH']];

export function ProgressGame({ skillId, skillName, construct, rating, language, isMatch = false, onComplete, onExit }: Props) {
  const t = text[language]; const [index, setIndex] = useState(0); const [answer, setAnswer] = useState<number | null>(null); const [correct, setCorrect] = useState(0); const [started, setStarted] = useState(Date.now()); const [result, setResult] = useState<GameResult | null>(null); const [memoryVisible, setMemoryVisible] = useState(true); const [memory, setMemory] = useState<string[]>([]); const [sequence] = useState(() => ['B', '7', 'M', '2'].sort(() => Math.random() - 0.5)); const [focus, setFocus] = useState<number[]>([]); const [grid] = useState(() => [...symbols, 'b', 'p', 'd', 'b', 'q', 'd', 'b', 'p'].sort(() => Math.random() - 0.5)); const [pair] = useState(() => wordPairs[Math.floor(Math.random() * wordPairs.length)]);
  useEffect(() => { if (skillId === 'memory') { const timer = window.setTimeout(() => setMemoryVisible(false), 3000); return () => window.clearTimeout(timer); } }, [skillId, started]);
  const finish = (score: number, total: number) => { const seconds = Math.max(1, Math.round((Date.now() - started) / 1000)); const delta = Math.round((score / total - 0.6) * (isMatch ? 35 : 10)); const next = { skillId, correct: score, total, seconds, delta, mode: isMatch ? 'match' as const : 'practice' as const }; setResult(next); onComplete(next); };
  const nextSound = () => { const score = correct; if (index === sound.length - 1) finish(score, sound.length); else { setIndex(index + 1); setAnswer(null); } };
  const replay = () => { setResult(null); setIndex(0); setAnswer(null); setCorrect(0); setMemory([]); setFocus([]); setMemoryVisible(true); setStarted(Date.now()); };
  if (result) return <div className="mx-auto flex min-h-[min(680px,calc(100vh-170px))] max-w-2xl items-center justify-center"><div className="w-full rounded-3xl border border-border bg-surface p-8 text-center shadow-xl"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-orange-100 text-[#e86f51]"><Trophy size={32} /></div><h1 className="text-3xl font-black text-text">{t.complete} 🎉</h1><div className="mt-7 grid grid-cols-3 gap-3"><Stat label={t.score} value={`${result.correct}/${result.total}`} /><Stat label={t.accuracy} value={`${Math.round(result.correct / result.total * 100)}%`} /><Stat label={t.time} value={`${result.seconds}s`} /></div><div className="my-7 rounded-2xl bg-gray-50 p-5"><div className="text-xs font-black uppercase text-text-muted">{t.rating} · {construct}</div><div className="mt-2 text-4xl font-black text-text">{rating} → {rating + result.delta}</div><div className={`font-black ${result.delta >= 0 ? 'text-green-600' : 'text-red-500'}`}>{result.delta >= 0 ? '↑' : '↓'} {Math.abs(result.delta)} {t.change}</div></div><div className="flex gap-3"><button onClick={onExit} className="flex-1 rounded-xl border border-border py-3 font-black text-text">{t.back}</button><button onClick={replay} className="flex-1 rounded-xl bg-[#e86f51] py-3 font-black text-white"><RotateCcw size={16} className="mr-2 inline" />{t.again}</button></div></div></div>;
  const header = <><div className="mb-4 flex items-center justify-between"><button onClick={onExit} className="inline-flex items-center gap-2 text-sm font-black text-text-muted"><ArrowLeft size={17} /> {t.exit}</button><span className="flex items-center gap-1 text-xs font-black text-text-muted"><Clock3 size={14} /> {skillName}</span></div><div className="mb-5 h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full bg-[#e86f51]" style={{ width: skillId === 'sound' ? `${(index + 1) / sound.length * 100}%` : '50%' }} /></div></>;
  return <div className="mx-auto max-w-2xl">{header}<div className="rounded-3xl border border-border bg-surface p-6 shadow-xl sm:p-8"><div className="mb-6 flex items-center gap-3"><div className="rounded-xl bg-orange-50 p-3 text-[#e86f51]"><Gamepad2 size={23} /></div><div><h1 className="text-2xl font-black text-text">{skillName}</h1><p className="text-sm font-semibold text-text-muted">{construct}</p></div></div>{skillId === 'sound' && <Sound t={t} index={index} answer={answer} onAnswer={(value) => { setAnswer(value); if (value === sound[index][2]) setCorrect(correct + 1); }} onNext={nextSound} />}{skillId === 'focus' && <div><h2 className="text-2xl font-black text-text">{t.find} “b”</h2><p className="mt-2 text-sm font-semibold text-text-muted">{t.choose}</p><div className="mt-7 grid grid-cols-4 gap-3">{grid.map((item, i) => <button key={`${item}-${i}`} onClick={() => setFocus(focus.includes(i) ? focus.filter(x => x !== i) : [...focus, i])} className={`aspect-square rounded-xl border-2 text-2xl font-black ${focus.includes(i) ? 'border-orange-500 bg-orange-100' : 'border-border bg-gray-50'}`}>{item}</button>)}</div><button onClick={() => finish(focus.filter(i => grid[i] === 'b').length, grid.filter(x => x === 'b').length)} className="mt-5 w-full rounded-xl bg-[#e86f51] py-3 font-black text-white">{t.submit}</button></div>}{skillId === 'memory' && <div><h2 className="text-2xl font-black text-text">{memoryVisible ? t.remember : t.repeat}</h2><div className="my-8 flex justify-center gap-3 rounded-2xl bg-purple-50 p-5">{(memoryVisible ? sequence : memory).map((item, i) => <span key={`${item}-${i}`} className="rounded-xl bg-white px-4 py-3 text-2xl font-black text-purple-700">{item}</span>)}</div>{!memoryVisible && <><div className="grid grid-cols-4 gap-3">{[...sequence, 'A', '9', 'R', '4'].map((item, i) => <button key={`${item}-${i}`} onClick={() => !memory.includes(item) && setMemory([...memory, item])} className="rounded-xl border-2 border-border p-3 text-xl font-black">{item}</button>)}</div><button disabled={memory.length !== sequence.length} onClick={() => finish(memory.filter((item, i) => item === sequence[i]).length, sequence.length)} className="mt-5 w-full rounded-xl bg-purple-600 py-3 font-black text-white disabled:opacity-40">{t.check}</button></>}</div>}{skillId === 'speed' && <div><h2 className="text-2xl font-black text-text">{t.match}</h2><div className="my-10 flex justify-center gap-5 text-3xl font-black"><span className="rounded-2xl bg-blue-50 p-5">{pair[0]}</span><span>?</span><span className="rounded-2xl bg-orange-50 p-5">{pair[1]}</span></div><div className="grid grid-cols-2 gap-3"><button onClick={() => finish(pair[0] === pair[1] ? 1 : 0, 1)} className="rounded-xl bg-green-500 py-4 font-black text-white">{t.yes}</button><button onClick={() => finish(pair[0] !== pair[1] ? 1 : 0, 1)} className="rounded-xl bg-red-500 py-4 font-black text-white">{t.no}</button></div></div>}</div></div>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-blue-50 p-4"><div className="text-2xl font-black text-text">{value}</div><div className="text-xs font-bold text-text-muted">{label}</div></div>; }
function Sound({ t, index, answer, onAnswer, onNext }: { t: Text; index: number; answer: number | null; onAnswer: (value: number) => void; onNext: () => void }) { const item = sound[index]; return <div><p className="mb-2 text-xs font-black uppercase text-[#e86f51]">{t.question} {index + 1} of {sound.length}</p><h2 className="text-2xl font-black text-text">{item[0]}</h2><p className="mt-2 text-sm font-semibold text-text-muted">{t.choose}</p><div className="mt-6 grid gap-3">{item[1].map((option, i) => <button key={option} onClick={() => answer === null && onAnswer(i)} className={`rounded-xl border-2 p-4 text-left font-black ${answer === i ? i === item[2] ? 'border-green-500 bg-green-50' : 'border-red-400 bg-red-50' : 'border-border'}`}>{String.fromCharCode(65 + i)}. {option}</button>)}</div>{answer !== null && <p className="mt-4 text-sm font-black">{answer === item[2] ? <><Check className="mr-1 inline" />{t.correct}</> : <><X className="mr-1 inline" />{t.wrong}</>}</p>}<button disabled={answer === null} onClick={onNext} className="mt-5 w-full rounded-xl bg-[#e86f51] py-3 font-black text-white disabled:opacity-40">{index === sound.length - 1 ? t.complete : t.next}</button></div>; }
